CONTRIBUTING.md
bases/ezs-python-server/Dockerfile
bases/ezs-python-server/README.md
bases/ezs-python-server/package.json
package.json
services/base-line-python/package.json

Last version of `@ezs/core` fixes error handling with traefik.

Fix traefik error handling in `ezs-python-server`

---

bases/ezs-python-server/Dockerfile
bases/ezs-python-server/README.md
bases/ezs-python-server/package.json
package.json
services/base-line-python/Dockerfile
services/base-line-python/package.json
services/base-line-python/swagger.json
services/base-line/Dockerfile
services/base-line/package.json
services/base-line/swagger.json

To be able to use [`[metrics]`](https://inist-cnrs.github.io/ezs/#/plugin-core?id=metrics) statement.

Update ezs/core to 3.3.0

---

.github/workflows/docker-build-on-merge.yml
services/base-line/package.json

At merge, the build-on-merge action failed, due to the protection of the main branch.
Let's try to push to the pull request's branch, hoping that it's still time.

build: Target a non-protected branch

---

.github/workflows/docker-build-on-merge.yml
.github/workflows/docker-build-on-push.yml
CONTRIBUTING.md
bases/ezs-python-server/Dockerfile
bases/ezs-python-server/README.md
bases/ezs-python-server/package.json
bases/python-node/Dockerfile
bases/python-node/README.md
bases/python-node/package.json
services/base-line-python/Dockerfile
services/base-line-python/README.md
services/base-line-python/package.json
services/base-line-python/swagger.json
services/base-line/Dockerfile
services/base-line/README.md
services/base-line/package.json
services/base-line/swagger.json
services/base-line/v1/no-accent.ini
services/base-line/v1/no-accent2.ini

Create a python-node docker image, because node 16 is no more available, and node 18 does not work on old docker versions.
User `daemon` launches the ezs server, because that's the user which ezmaster-webdav uses.

Use node 16 instead of node 18

---

bases/ezs-python-saxon-server/Dockerfile
bases/ezs-python-saxon-server/README.md
bases/ezs-python-saxon-server/package.json
bases/ezs-python-server/Dockerfile
bases/ezs-python-server/README.md
bases/ezs-python-server/package.json
bases/python-node/Dockerfile
bases/python-node/README.md
bases/python-node/package.json
services/base-line-python/Dockerfile
services/base-line-python/README.md
services/base-line-python/package.json
services/base-line-python/swagger.json
services/base-line/Dockerfile
services/base-line/README.md
services/base-line/package.json
services/base-line/swagger.json
services/terms-extraction/Dockerfile
services/terms-extraction/README.md
services/terms-extraction/package.json
services/terms-extraction/swagger.json
template/Dockerfile

When running `ws-terms-extraction@1.0.0`, the root page of the server return a 404, and the logs contained:
```log
npm ERR! code EACCES
npm ERR! syscall open
npm ERR! path /root/.npm/_cacache/tmp/1b088e67
npm ERR! errno -13
npm ERR! 
npm ERR! Your cache folder contains root-owned files, due to a bug in
npm ERR! previous versions of npm which has since been addressed.
npm ERR! 
npm ERR! To permanently fix this problem, please run:
npm ERR!   sudo chown -R 1:1 "/root/.npm"
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-01-19T07_54_39_306Z-debug-0.log
npm notice 
npm notice New major version of npm available! 8.19.4 -> 10.3.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.3.0
npm notice Run npm install -g npm@10.3.0 to update!
npm …
```

fix(python-node): Cache happen to be created in /root/.npm

---

CONTRIBUTING.md
services/terms-extraction/swagger.json

During transition phase: set the correct url in `swagger.json`, enable `x-profil` and set it to `Standard` to indicate that the URL is the internal one in production.

chore(terms-extraction): Set production url

---

bin/dry-run.sh
bin/update-images.sh
bin/wet-run.sh

Because when `ezs` packages are updated, the `ezs-python-server` has to be updated, and then many other depending services, the template, ...

Add a script to facilitate the upgrade of images depending on a base image

---

services/biblio-ref/examples.http
services/biblio-ref/tests.hurl
services/biblio-ref/v1/validate.py

now service return the doi if found AND a single key "status" (instead of retracted + found) but the value's type is no more boolean.
Example of output :
- "error_data" (data not string),
-  "found",
-  "not_found" (no doi or doi doesn't match) ,
-  "error_service" (when response from crossref api isn't a 200 or 404)

feat(biblio-ref): update output of service

---

.vscode/settings.json
CONTRIBUTING.md
SCRIPTS.md
bin/insert-description.sh
package.json
services/terms-extraction/v1/teeft/en.ini
services/terms-extraction/v1/teeft/fr.ini
services/terms-extraction/v1/teeft/with-numbers/en.ini
services/terms-extraction/v1/teeft/with-numbers/fr.ini
services/terms-extraction/v1_teeft_en.md
services/terms-extraction/v1_teeft_fr.md
services/terms-extraction/v1_teeft_with-numbers_en.md
services/terms-extraction/v1_teeft_with-numbers_fr.md

Convert a Markdown file, named after the path of the `.ini`, to a unique line, that will replace the `post.description` metadata of that `.ini`.
If the `post.description` does not exist, it is appended after the `post.summary` line.
See https://github.com/Inist-CNRS/ezs/commit/8f342f11ca4fb67aef44c8d76f4dba68ce891b32

Add script to insert description into .ini metadata

---

services/biblio-ref/README.md
services/biblio-ref/package.json
services/biblio-ref/swagger.json

release ws-biblio-ref@1.1.0

---

services/affiliation-rnsr/Dockerfile
services/chem-ner/Dockerfile
services/diseases-ner/Dockerfile
services/terms-extraction/Dockerfile
template/Dockerfile

It was wrongly located: all files were copied into `/app/public`, including `config.json`.
But the [`ezs-python-server`'s `Dockerfile`](https://github.com/Inist-CNRS/web-services/blob/a2ec787a3a1c0c4fa60a31be64ef9f8c7660edad/bases/ezs-python-server/Dockerfile#L6) states that ezmaster's configuration file path is `/app/config.json`:
```Dockerfile
RUN apt update && apt install -y tini && \
echo '{ \
"httpPort": 31976, \
"configPath": "/app/config.json", \
"dataPath": "/app/public" \
}' > /etc/ezmaster.json
```

Make ezmaster take config.json into account

---

services/data-computer/README.md
services/data-computer/package.json
services/data-computer/swagger.json

#75 did fix the `/tmp` problem
(see #68)
But the tag seems to not match the code in #75 (there was problem at `git push --tags`).
Let's create a patch version to get the fixed files in the Docker image.

data-computer: fix /tmp

---

services/data-computer/Dockerfile
services/data-computer/README.md
services/data-computer/package.json
services/data-computer/swagger.json

Need scipy==1.10.1 becauser gensim is using a depreciate function of scipy in v1.11+

fix(data-computer): fix dependencies of LDA route

---

services/affiliations-tools/Dockerfile
services/affiliations-tools/README.md
services/affiliations-tools/package.json
services/affiliations-tools/swagger.json
services/affiliations-tools/tests.hurl
services/affiliations-tools/v1/rnsr/info.ini

To take 2023 RNSR's data into account, one has to update to `@ezs/conditor@2.12.0`.
Side effect: numbers are no longer strings, but... numbers.
See [`@ezs/conditor`](https://github.com/Inist-CNRS/ezs/pull/413): Inist-CNRS/ezs#413
See [ws-data](https://github.com/Inist-CNRS/ws-data/tree/master/rnsr).

affiliations-tools: update ezs conditor to 2.12

---

services/astro-ner/swagger.json

The base image change did not work straight.
```Dockerfile
FROM python:3.9-slim-bullseye as dvcfiles
WORKDIR /dvc
RUN apt update && apt -y install git curl
RUN pip install dvc[webdav]==3.42.0
RUN --mount=type=secret,id=webdav_login \
--mount=type=secret,id=webdav_password \
--mount=type=secret,id=webdav_url \
git init && \
dvc init && \
dvc remote add -d webdav-remote "$(cat /run/secrets/webdav_url)" && \
dvc remote modify --local webdav-remote user "$(cat /run/secrets/webdav_login)" && \
dvc remote modify --local webdav-remote password "$(cat /run/secrets/webdav_password)"
COPY ./v1/model.dvc /dvc
RUN dvc pull -v
RUN cat model/* > model.pt
FROM cnrsinist/ezs-python-pytorch-server:py3.9-no16-1.1.1
USER root
ENV HF_HOME=/app/public/.huggingface
RUN npm install \
@ezs/storage@3.2.3
WORKDIR …
```

[astro-ner]: Deploy 1.0.8

---

bin/get-production-versions.sh
services/base-line-python/package.json

Get the version of the service in production, according to the `swagger.json` it returns.
Example:
```bash
$ bin/get-production-versions.sh services/*
address-kit	2.1.2
affiliation-rnsr	3.4.4
affiliations-tools	1.1.8
ark-tools	1.28.3
astro-ner	1.0.10
authors-tools	2.5.4
base-line	1.0.13
base-line-python	
biblio-ref	1.4.1
biblio-tools	4.0.5
chem-ner	3.0.8
data-computer	2.12.6
data-termsuite	3.0.4
data-workflow	1.2.9
data-wrapper	1.3.5
diseases-ner	1.0.14
domains-classifier	1.5.2
funder-ner	1.0.4
hal-classifier	4.0.6
irc3-species	1.1.5
ner-tagger	1.0.8
nlp-tools2	2.0.5
pdf-text	1.1.2
sciencemetrix-classification	2.0.2
terms-extraction	1.6.2
```
> **Note**: in the example, `affiliation-rnsr`'s version according to `package.json` is `2.1.3`. 
> **Note2**: `base-line-python` does not exist in …

Add get-production-versions shell script

---

template/config.json

Because more is too much (with the current machine).

[template] Reduce default concurrency

---

bin/test-services-tsv.sh

To Display test results of all services in production in TSV format.
Example:
```bash
./bin/test-services-tsv.sh services/* > /tmp/2024-07-22-services.tsv
```
You can even translate it to Markdown using [`tsv-to-markdown`](https://www.npmjs.com/package/csv-to-markdown):
| service                      | version | result |
| ---------------------------- | ------- | ------ |
| address-kit                  | 2.1.2   | ✅      |
| affiliation-rnsr             | 2.1.9   | ✅      |
| affiliations-tools           | 1.1.8   | ❌      |
| ark-tools                    | 1.28.3  | n/a    |
| astro-ner                    | 1.0.10  | ✅      |
| authors-tools                | 2.5.4   | ✅      |
| base-line                    | 1.0.13  | ✅      |
| base-line-python             |         | n/a    |
| …

Add bin/test-services-tsv.sh

---

services/data-termsuite/tests.hurl

Because URLs are not permanent.
Error from automated tests:
```log
{
"type": "Data corruption error",
"scope": "data",
"date": "2024-08-07T04:05:04.041Z",
"message": "item #1 [delegate] <Error: [swing] <Error: [URLFetch] <Error: Not Found>>>",
"func": "delegate",
"params": {
"file": "Expression::\"recorder.cfg\""
},
"traceback": [
"\\t\\t    at /app/node_modules/@ezs/basics/lib/request.js:12:17",
"\\t\\t    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
"\\t\\t    at async Object.URLFetch (/app/node_modules/@ezs/basics/lib/url-fetch.js:60:22)",
"\\t    at Feed.push (/app/node_modules/@ezs/core/lib/engine.js:186:27)",
"\\t    at Feed.write (/app/node_modules/@ezs/core/lib/feed.js:35:12)",
"\\t    at Feed.send (/app/node_modules/@ezs/core/lib/feed.js:101:10)",
"\\t …
```

[data-termsuite]: Tests won't use webhook.site

---

.vscode/extensions.json
.vscode/settings.json
services/data-computer/v1/graph-segment.ini
services/data-computer/v1/lda-segment.cfg

See <https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker>.
`Ctrl`-`.` is the shortcut.
These extensions are recommended, but not required.

[vscode] add spelling extensions

---

services/data-computer/tests.hurl

Because sometimes delays of 1 second are not enough, double them.

[data-computer]: Increase delays

---

services/data-termsuite/tests.hurl

Because often tests on production fail, only because of delays.

[data-termsuite]: Increase delays x1.5

---

services/data-computer/Dockerfile
services/data-computer/README.md
services/data-computer/package.json
services/data-computer/swagger.json

Instead of specifying older ones.
Historically it may have been done to use newer versions, but it is no more the case.

[data-computer]: Use ezs packages from base image

---

package-lock.json
services/loterre-resolvers/README.md
services/loterre-resolvers/docker-entrypoint.sh
services/loterre-resolvers/package.json
services/loterre-resolvers/swagger.json
services/loterre-resolvers/v1/combine.cfg

Because in /tmp they were removed automatically by cleanup scripts (only on production machines).

[loterre-resolvers]: Move databases into /app/public

---

.github/workflows/test-and-publish-on-tag.yml
.github/workflows/test-on-branch.yml
bin/build-and-test.sh
bin/generate-example-tests.mjs
bin/test-ip-services.sh
bin/test-on-branch.sh
bin/test-on-tag.sh
bin/test-service.sh
bin/test-services-tsv.sh
bin/test-services.sh
package.json

Version 5 of hurl provide better error messages, which would be profitable while writing tests and understanding error messages of daily tests.
> [!WARNING]
> Tests are now executed in parallel, use `--jobs 1` option to avoid that.
> [!NOTE]
> Don't forget [daily tests](https://vegitlab.intra.inist.fr/tdm/ws-cron-testing).

[hurl] update to version 5

---

services/loterre-resolvers/Dockerfile
services/loterre-resolvers/README.md
services/loterre-resolvers/docker-entrypoint.sh
services/loterre-resolvers/package.json
services/loterre-resolvers/swagger.json
services/loterre-resolvers/v1/combine.cfg

A new version of `@ezs/core` was done to avoid the swagger performance struggle when numerous files were present at the server's root directory (for `loterre-resolvers`, there is roughly 2 millions files, taking 1 minute to be scanned to build `swagger.json`).
Inist-CNRS/ezs#430
Let's make a `loterre-resolvers` version using that new version of `@ezs/core`.

[loterre resolvers] fix swagger perf

---

CONTRIBUTING.md
bin/test-ip-services.sh
bin/test-on-branch.sh
bin/test-on-tag.sh
services/affiliations-tools/tests.hurl

Voir #228
Certains tests doivent être désactivés dans certaines conditions: quand ils font appel à un autre web service du dépôt en production, et qu'ils sont lancés d'une IP non autorisée.
C'est pourquoi on utilise une variable `blocked` dans `tests.hurl` pour savoir si l'IP d'où on lance les tests est bloquée ou non.  
Ces cas devraient être relativement rares (seulement 8 recensés au 22 janvier 2025).

[tests] desactivate blocked tests

---

services/data-workflow/tests.hurl

Because sometimes they're not enough.

[data-workflow]: Increase waiting time

---

services/loterre-resolvers/Dockerfile
services/loterre-resolvers/README.md
services/loterre-resolvers/docker-entrypoint.sh
services/loterre-resolvers/package.json
services/loterre-resolvers/swagger.json

So we copy `.tgz` in `/app/data0` (during buit) before extracting them in `/app/data` (at run).
See https://github.com/Inist-CNRS/web-services/issues/194#issuecomment-2621729925

[loterre-resolvers] /app/data overwritten by Persistent Volume Claim

---

bin/test-on-tag.sh
services/text-clustering/README.md
services/text-clustering/package.json
services/text-clustering/swagger.json
services/text-clustering/v1/clustering.py

On small corpus (< 30), couldn't use auto clustering.
This patch is useful for tests (like in IA Factory)

[text clustering] fix a bug on small corpus

---

README.md
package.json

There was a mix between two branches (see 320ce4cb1624dda33c5ac07d365df43194b3e15f).

[build] fix package json data blame workspace

---

services/data-wrapper/README.md
services/data-wrapper/package.json
services/data-wrapper/swagger.json
services/data-wrapper/tests.hurl
services/data-wrapper/v1/csv.ini
services/data-wrapper/v1/txt.ini

Add a wrapper that converts a text file to a corpus file (`.tar.gz` containing one JSON file with `id` and `value` fields, `value` containing the text).

[data-wrapper] Add txt

---

services/data-wrapper/README.md
services/data-wrapper/package.json
services/data-wrapper/swagger.json
services/data-wrapper/tests.hurl
services/data-wrapper/v1/csv.ini

When the first line of a CSV contains an empty value column, it isn't  validated.
So, the wrapper now replaces empty values with `"n/a"`.

[data-wrapper] add default value to csv

---

services/data-wrapper/tests.hurl
services/data-wrapper/v1/fields/csv.ini
services/data-wrapper/v1/fields/json.ini
services/data-wrapper/v1/fields/jsonl.ini

À l’image de la route `fields/csv`, créer un service `fields/json` qui renvoie les noms des champs de premier niveau d’un JSON.

[data-wrapper] Add fields/json & jsonl

---

services/text-clustering/README.md
services/text-clustering/package.json
services/text-clustering/swagger.json
services/text-clustering/v1/noise-process.py

I tried to use [swing] with ezs (instead of using another script with fork ; `noise-process.py`) but the streams is break when no noisy documents are returned

[text clustering] fix noise detect output
