CONTRIBUTING.md
bin/generate-example-metadata.mjs
package.json
services/base-line-python/Dockerfile
services/base-line-python/examples.http
services/base-line/Dockerfile
services/base-line/examples.http
services/base-line/v1/echo/csv.ini
services/base-line/v1/echo/json.ini
services/base-line/v1/echo/raw.ini
services/base-line/v1/true/csv.ini
services/base-line/v1/true/json.ini

To facilitate the writing for the example metadata, add a script.

Add generate-example-metadata script

---

SCRIPTS.md
package.json

Add scripts help

---

CONTRIBUTING.md
bin/test-service.sh
bin/test-services.sh
package.json

Install [hurl](https://hurl.dev/), and add scripts to run the generated tests.

Add tests runners

---

README.md

Public pages for docker images changed URL.

Fix bad links to docker hub repositories

---

.vscode/settings.json
CONTRIBUTING.md

Before creating a pull request, you need to create a git branch.
Let's document the naming of the branchs.

Document the creation of a branch

---

bases/ezs-python-server/Dockerfile
bases/ezs-python-server/README.md
bases/ezs-python-server/package.json

To make old version of docker run.
Closes #11

build(ezs-ptyhon-server): Use an older version node

---

CONTRIBUTING.md
README.md
SCRIPTS.md
bin/create-service-from-template.sh
package.json
template/.dockerignore
template/Dockerfile
template/README.md
template/examples.http
template/package.json
template/swagger.json

Run scripts from root (workspaces) + template

---

SCRIPTS.md
bin/generate-example-tests.mjs
bin/test-service.sh
bin/test-services.sh
package.json

And use the right path to services.

Generate only one file, using a host variable

---

template/Dockerfile

I forgot to modify the template's Dockerfile in #24

build: Update to ezs-python-server:py3.9-no16-1.0.6

---

CONTRIBUTING.md
template/config.json

To set EZS_TITLE and EZS_DESCRIPTION automatically.

Add config.json to the template

---

.github/workflows/docker-build-on-push.yml
.gitignore
README.md
bin/create-env.sh
package.json
services/biblio-ref/.dockerignore
services/biblio-ref/Dockerfile
services/biblio-ref/README.md
services/biblio-ref/examples.http
services/biblio-ref/package.json
services/biblio-ref/swagger.json
services/biblio-ref/tests.hurl
services/biblio-ref/v1/annulled.csv.dvc
services/biblio-ref/v1/validate.ini
services/biblio-ref/v1/validate.py

Fixed Dockerfile. We'll have to fix it again because I "cheated" by copying /v1 without using .dockerignore

Services/biblio ref/create service

---

.github/workflows/docker-build-on-tag.yml
README.md
bin/create-env.sh
package.json
services/affiliation-rnsr/.dockerignore
services/affiliation-rnsr/Dockerfile
services/affiliation-rnsr/README.md
services/affiliation-rnsr/config.json
services/affiliation-rnsr/examples.http
services/affiliation-rnsr/package.json
services/affiliation-rnsr/swagger.json
services/affiliation-rnsr/tests.hurl
services/affiliation-rnsr/v2/affiliation/rnsr.ini
services/affiliation-rnsr/v2/affiliation/rnsr.py
services/affiliation-rnsr/v3/affiliation/models.dvc
services/affiliation-rnsr/v3/affiliation/rnsr.ini
services/affiliation-rnsr/v3/affiliation/rnsr.py

There is an error : can build the image but can't start it.
To know : 
- I build it using inistcnrs/lodex-workers-python:4.0.11 instead of cnrsinist/ezs-python-server:py3.9-no16-1.0.6.
(beacause fasttext has some issues for python 3.9+)
- have 2 roots instead of one (v2 and v3). I changed it in .dockerignore.

refactor(affiliation-rnsr): migrate service affiliation-rnsr

---

services/affiliation-rnsr/swagger.json
services/base-line-python/swagger.json
services/base-line/swagger.json
services/biblio-ref/swagger.json
services/terms-extraction/swagger.json

forgot to change x-profile and port here

Services/affiliation rnsr/migrate service

---

services/biblio-ref/Dockerfile
services/biblio-ref/README.md
services/biblio-ref/examples.http
services/biblio-ref/package.json
services/biblio-ref/swagger.json
services/biblio-ref/tests.hurl
services/biblio-ref/v1/validate.ini
services/biblio-ref/v1/validate.py

new feature : now, ws works on references without dois.
- Generated new tests
- new doc
- changed code

Services/biblio ref/feature

---

CONTRIBUTING.md

non optimal pipeline for now (look at first point and 'remarque') but non-breaking with git architecture

docs(CONTRIBUTING.md): added dvc subsection

---

bin/publish.sh

So that OpenApi 3.0 as well as OpenApi 3.1 can be published

Allow info description in publish.sh

---

services/biblio-ref/.dockerignore
services/biblio-ref/Dockerfile
services/biblio-ref/README.md
services/biblio-ref/package.json
services/biblio-ref/swagger.json
services/biblio-ref/v1/validate.py

- No more use DVC (now dl it with perma URL while building)
- no more use pandas (use bash to process my doi's list)

build(biblio-ref): now dl the retracted doi list at docker build

---

services/data-wrapper/Dockerfile
services/data-wrapper/README.md
services/data-wrapper/package.json
services/data-wrapper/swagger.json
services/data-wrapper/v1/fields/csv.ini

see https://github.com/Inist-CNRS/ezs/pull/403

the shift statement does not stop the stream

---

services/data-wrapper/Dockerfile
services/data-wrapper/README.md
services/data-wrapper/package.json
services/data-wrapper/swagger.json

upgrade ezs/conditor

---

bases/ezs-python-pytorch-server/Dockerfile
bases/ezs-python-pytorch-server/README.md
bases/ezs-python-pytorch-server/package.json
services/astro-ner/Dockerfile
services/astro-ner/README.md
services/astro-ner/package.json
services/astro-ner/swagger.json

To simplify Dockerfile, and lighten the docker image.

[astro-ner]: use pytorch base image

---

README.md
package.json

Damn web GitHub interface to resolve conflicts!

Fix conflicts

---

services/terms-extraction/Dockerfile
services/terms-extraction/README.md
services/terms-extraction/config.json
services/terms-extraction/package.json
services/terms-extraction/swagger.json

[terms-extraction] freeze numpy version and fix missing config

---

services/sciencemetrix-classification/Dockerfile
services/sciencemetrix-classification/README.md
services/sciencemetrix-classification/package.json
services/sciencemetrix-classification/swagger.json

[sciencemetrix-classification] freeze numpy version

---

services/data-wrapper/Dockerfile
services/data-wrapper/README.md
services/data-wrapper/package.json
services/data-wrapper/swagger.json

[data-wrapper] add missing config modification

---

services/affiliations-tools/Dockerfile
services/affiliations-tools/README.md
services/affiliations-tools/config.json
services/affiliations-tools/package.json
services/affiliations-tools/swagger.json

[affiliation-tools] Opimise build and add missing config

---

bin/test-ip-services.sh
bin/test-services.sh

Mainly add a script to test services using their IP addresses, to check if a problem in remote tests were a network problem or not.

Improve tests scripts

---

services/affiliation-rnsr/Dockerfile
services/affiliation-rnsr/README.md
services/affiliation-rnsr/config.json
services/affiliation-rnsr/package.json
services/affiliation-rnsr/swagger.json

Fix version number #116 
Fix returning anything (due to numpy last version) #117

[affiliation-rnsr] fix numpy, version

---

services/affiliation-rnsr/Dockerfile

fix(affiliation-rnsr) config.json not taken into account in ezmaster

---

package.json

Use version 4.3.2 which fixes 4.3.0

Fix hurl version

---

services/ner-tagger/Dockerfile
services/ner-tagger/README.md
services/ner-tagger/config.json
services/ner-tagger/package.json
services/ner-tagger/swagger.json
services/ner-tagger/v1/geoTagger/geoTagger.py

Use a version of the model compatible with the version of flair used
Fix #156

[ner-tagger]: Fix model version

---

services/affiliations-tools/README.md
services/affiliations-tools/examples.http
services/affiliations-tools/package.json
services/affiliations-tools/swagger.json
services/affiliations-tools/tests.hurl
services/affiliations-tools/v1/ror/get-id.ini
services/affiliations-tools/v1/ror/get-id.py

Bug avec la sortie standard (print dans le code).

fix(affilliations-tools/ror): fix bug print

---

services/biblio-ref/README.md
services/biblio-ref/package.json
services/biblio-ref/swagger.json
services/biblio-ref/v1/validate-pdf.ini
services/biblio-ref/v1/validate-pdf.py
services/biblio-ref/v1/validate-url.py

- management error (if references of PDF can't be extract)
- new output for PDF

feat(biblio-ref): new output for validate-pdf

---

.vscode/settings.json
services/biblio-tools/README.md
services/biblio-tools/package.json
services/biblio-tools/swagger.json
services/biblio-tools/v2/openalex/works/expand.ini

[biblio-tools] fix openalex/v2/works/expand abstract

---

services/biblio-tools/README.md
services/biblio-tools/package.json
services/biblio-tools/swagger.json
services/biblio-tools/v2/openalex/works/expand.ini

Especially those containing french quotes.
See #206

[biblio-tools] Some abstracts were strangley rebuilt

---

services/diseases-ner/README.md
services/diseases-ner/package.json
services/diseases-ner/swagger.json
services/diseases-ner/v1/diseases/tagger.py

When an entity is detect in the end of the text, a bug occured (because we want to see if the token after is an entity or not). Fixed it and optimized it.

fix(diseases-ner): fix how to get entities

---

services/chem-ner/README.md
services/chem-ner/package.json
services/chem-ner/swagger.json
services/chem-ner/v1/chem/tagger.py

When an entity is detect in the end of the text, a bug occured (because we want to see if the token after is an entity or not). Fixed it and optimized it.

fix(chem-ner): fix how to get entities

---

README.md
package.json
services/funder-ner/README.md
services/funder-ner/package.json
services/funder-ner/swagger.json
services/funder-ner/tests.hurl
services/funder-ner/v1/tagger.py

Fix output to be a list and not a string representation of a list

[funder-ner] Fix:Output will now be considered as list as it was expected

---

services/text-clustering/Dockerfile
services/text-clustering/README.md
services/text-clustering/package.json
services/text-clustering/swagger.json
services/text-clustering/tests.hurl
services/text-clustering/v1/clustering.ini
services/text-clustering/v1/clustering.py
services/text-clustering/v1/noise.py

- change hdbscan algo to kmeans
- now user have to use v1/noise to detect noise

Services/text clustering/change algo

---

services/affiliations-tools/tests.hurl
services/affiliations-tools/v1/expand.ini

See #234 : tests mechanism was changed, but not tested.
That's why we create this fake change: to see if it works well.

[affiliations tools] Check that tests now work in the CI

---

services/data-workflow/tests.hurl
services/data-workflow/v1/base-line.ini

To make them pass on GitHub.
See #228

[data-workflow]: Skip test depending on blocked variable

---

services/text-clustering/tests.hurl
services/text-clustering/v1/clustering.ini
services/text-clustering/v1/clustering.py

`v1/clustering` uses `terms-extraction.services.istex.fr/v1/teeft`, which is not accessible from GitHub Actions.
See #228

[text clustering] skip test on GitHub

---

services/data-workflow/tests.hurl

[data-workflow]: Increase waiting time again

---

services/data-workflow/tests.hurl

Sometimes, production is loaded

[data-workflow]: Increase delay again and again

---

services/loterre-resolvers/Dockerfile
services/loterre-resolvers/README.md
services/loterre-resolvers/docker-entrypoint.sh
services/loterre-resolvers/package.json
services/loterre-resolvers/swagger.json
services/loterre-resolvers/v1/combine.cfg

To make it work with k3s.
See #194

[loterre resolvers] Move databases to /app/data

---

services/data-homogenise/README.md
services/data-homogenise/package.json
services/data-homogenise/swagger.json
services/data-homogenise/tests.hurl
services/data-homogenise/v1/group.ini
services/data-homogenise/v1/group.py

Add the route v1/group
Group keywords regard to their similarity distance instead of homogenise them.

[data-homogenise] add route for ReLM

---

services/biblio-tools/README.md
services/biblio-tools/package.json
services/biblio-tools/swagger.json
services/biblio-tools/tests.hurl
services/biblio-tools/v2/hal/works/expandByHalId.ini

Demande d'@AnaelKremer et Carine: récupérer une notice HAL (depuis HAL) à partir de son HalID.

[biblio-tools] add expand by hal

---

services/data-computer/tests.hurl
services/data-homogenise/tests.hurl
services/data-rapido/tests.hurl
services/data-termsuite/tests.hurl
services/data-thesesul/tests.hurl
services/data-topcitation/tests.hurl
services/data-workflow/tests.hurl
services/data-wrapper/tests.hurl

To avoid asking for a result before it exists.

test: Increase delays

---

services/pdf-text/Dockerfile
services/pdf-text/README.md
services/pdf-text/package.json
services/pdf-text/swagger.json
services/pdf-text/v1/pdf2txt.py

Add minimal treatment to enable docx.
We don't want to show this feature to users : we enable it for Coara.
So there is no test and no update in istex TDM.

[pdf-text] : now can process docx

---

services/data-workflow/README.md
services/data-workflow/package.json
services/data-workflow/swagger.json
services/data-workflow/tests.hurl
services/data-workflow/v1/retrieve-csv.ini
services/data-workflow/v1/retrieve-flatten-csv.ini
services/data-workflow/v1/teeft-en.ini
services/data-workflow/v1/teeft-fr.ini
services/data-workflow/v1/teeft.cfg

Because tag-cloud is not Teeft.
It's... tag cloud. :face_with_diagonal_mouth: 
(and does not work on a 1-document corpus)

[data-workflow] Add teeft

---

services/data-workflow/README.md
services/data-workflow/package.json
services/data-workflow/swagger.json
services/data-workflow/v1/text-summarize-pdf.cfg

Now use the route v1/en-pdf instead of ws `pdf-text` + v1/en

[data-workflow] update text-summarize for TDM Factory
